### ISSUE TITLE
uninitialized constant Oystercard

### ISSUE THREAD

**Issue by BecaLParker** [charlie-casserly/oyster-card#1]
https://github.com/makersacademy/course/blob/master/oystercard/03_debugging.md

**Comment by BecaLParker** [comment]
ameError:
  uninitialized constant Oystercard
# ./spec/oystercard_spec.rb:1:in `<top (required)>'

- [x] create an Ostercard class

**Comment by charlie-casserly** [comment]
https://github.com/charlie-casserly/oyster-card/commit/250bd3d4e9ace1abcaf09c673d6dd08f32498e92
